/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ariboss
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(this);
        jTextField_usrlogin.requestFocus();
    }

    public void refresh(){
        jTextField_usrlogin.setText("");
        jPasswordField_login.setText("jPasswordfield1");
        jTextField_usrlogin.requestFocus();
    }
    
    public void refresh2(){
        jTextField_nama.setText("");
        jTextField_usia.setText("");
        jTextField_usrdftr.setText("");
        jPasswordField_paswdaftar.setText("jPasswordfield1");
        jPasswordField_konfir.setText("jPasswordfield1");
        jTextField_nama.requestFocus();
    }
    
    public void cekusername(){
        java.sql.Connection conn = new Koneksi.koneksi().connect();
        try{
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet res = stmt.executeQuery("select *from pengguna where username ='"+jTextField_usrdftr.getText()+"'");
            while(res.next()){
                jTextField_usrdftr.setText(res.getString("username"));
                JOptionPane.showMessageDialog(null, "USERNAME TELAH DIGUNAKAN !!!");
                jTextField_usrdftr.setText("");
                jTextField_usrdftr.requestFocus();
            }
        }catch(SQLException ex){
            
        }
    }
    
    public void login(){
        java.sql.Connection conn= new Koneksi.koneksi().connect();            
        try{
            java.sql.PreparedStatement stmt=conn.prepareStatement("insert into login (username,status ) values (?,?)");
            try{           
                stmt.setString(1,jTextField_usrlogin.getText()); 
                stmt.setString(2,jLabel_status2.getText());                       
                stmt.executeUpdate();
                refresh();
            } catch(SQLException ex){               
            }
        }catch(Exception e){

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tampilan1 = new Kelas.tampilan();
        tampilan2 = new Kelas.tampilan();
        tampilan3 = new Kelas.tampilan();
        tampilan4 = new Kelas.tampilan();
        tampilan5 = new Kelas.tampilan();
        tampilan6 = new Kelas.tampilan();
        tampilan7 = new Kelas.tampilan();
        tampilan8 = new Kelas.tampilan();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_usrlogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField_login = new javax.swing.JPasswordField();
        jButton_batal = new javax.swing.JButton();
        jButton_login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField_nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_usia = new javax.swing.JTextField();
        jTextField_usrdftr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField_paswdaftar = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField_konfir = new javax.swing.JPasswordField();
        jButton_buat = new javax.swing.JButton();
        jButton_batalbuat = new javax.swing.JButton();
        jLabel_status = new javax.swing.JLabel();
        jLabel_status2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM PAKAR DETEKSI KERUSAKAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENGINE MOUNTING");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextField_usrlogin.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_usrlogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_usrlogin.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_usrlogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_usrlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usrloginMouseClicked(evt);
            }
        });
        jTextField_usrlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usrloginKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_usrloginKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");

        jPasswordField_login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_login.setText("jPasswordField1");
        jPasswordField_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_loginKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_loginKeyTyped(evt);
            }
        });

        jButton_batal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancel (2).png"))); // NOI18N
        jButton_batal.setText("BATAL");
        jButton_batal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_batal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_batalActionPerformed(evt);
            }
        });

        jButton_login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next.png"))); // NOI18N
        jButton_login.setText("LOGIN");
        jButton_login.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton_login.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*buat akun");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAMA");

        jTextField_nama.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nama.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_namaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_namaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USIA");

        jTextField_usia.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_usia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_usia.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_usia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_usia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_usiaKeyTyped(evt);
            }
        });

        jTextField_usrdftr.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_usrdftr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_usrdftr.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_usrdftr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_usrdftr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usrdftrKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_usrdftrKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USERNAME");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD");

        jPasswordField_paswdaftar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_paswdaftar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_paswdaftar.setText("jPasswordField1");
        jPasswordField_paswdaftar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_paswdaftarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_paswdaftarKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KONFIRMASI");

        jPasswordField_konfir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_konfir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_konfir.setText("jPasswordField1");
        jPasswordField_konfir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_konfirKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_konfirKeyTyped(evt);
            }
        });

        jButton_buat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_buat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hand.png"))); // NOI18N
        jButton_buat.setText("BUAT");
        jButton_buat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_buat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buatActionPerformed(evt);
            }
        });

        jButton_batalbuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_batalbuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancel (2).png"))); // NOI18N
        jButton_batalbuat.setText("BATAL");
        jButton_batalbuat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_batalbuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_batalbuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_batal))
                            .addComponent(jPasswordField_login, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_usrlogin, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_buat, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_batalbuat))
                            .addComponent(jTextField_usrdftr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField_paswdaftar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField_konfir, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jTextField_usia))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_usrlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_batal)
                    .addComponent(jButton_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_usrdftr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordField_paswdaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField_konfir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_batalbuat)
                    .addComponent(jButton_buat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_status.setText("PENGGUNA");

        javax.swing.GroupLayout tampilan8Layout = new javax.swing.GroupLayout(tampilan8);
        tampilan8.setLayout(tampilan8Layout);
        tampilan8Layout.setHorizontalGroup(
            tampilan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilan8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampilan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilan8Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_status2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_status))
                    .addGroup(tampilan8Layout.createSequentialGroup()
                        .addGroup(tampilan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tampilan8Layout.setVerticalGroup(
            tampilan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilan8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tampilan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tampilan8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(tampilan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_status)
                            .addComponent(jLabel_status2))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tampilan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tampilan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_batalActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton_batalActionPerformed

    private void jButton_batalbuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_batalbuatActionPerformed
        // TODO add your handling code here:
        refresh2();
    }//GEN-LAST:event_jButton_batalbuatActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
        java.sql.Connection conn = new Koneksi.koneksi().connect();
        try{
        if(jTextField_usrlogin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI USERNAME !!!");
            jTextField_usrlogin.requestFocus();
        }
        else if(jPasswordField_login.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI PASSWORD !!!");
            jPasswordField_login.requestFocusInWindow();
        }
        else{
        java.sql.Statement stmt = conn.createStatement();
        java.sql.ResultSet res = stmt.executeQuery("select *from pengguna where username= '"+jTextField_usrlogin.getText()+"'");
        if(res.next()){
            jLabel_status2.setText(res.getString("status"));
            if(jPasswordField_login.getText().equals(res.getString("password")) && jLabel_status.getText().equals("ADMIN")){
                login();
                new utama().show();
                dispose();
            }
            else if(jPasswordField_login.getText().equals(res.getString("password")) && jLabel_status.getText().equals("PENGGUNA")){
                login();
                new utama().show();
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "USERNAME DAN PASSWORD SALAH !!!");
                refresh();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "USERNAME DAN PASSWORD SALAH !!!");
            refresh();
        }
        }
        }catch(SQLException ex){
            
        }        
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_buatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buatActionPerformed
        // TODO add your handling code here:
        cekusername();
        if(jTextField_nama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI NAMA !!!");
            jTextField_nama.requestFocus();
        }
        else if(jTextField_usia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI USIA !!!");
            jTextField_usia.requestFocus();
        }
        else if(jTextField_usrdftr.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI USERNAME !!!");
            jTextField_usrdftr.requestFocus();
        }
        else if(jPasswordField_paswdaftar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI PASSWORD !!!");
            jPasswordField_paswdaftar.requestFocus();
        }
        else if(jPasswordField_konfir.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ISI KONFIRMASI PASSWORD !!!");
            jPasswordField_konfir.requestFocus();
        }
        else if(!jPasswordField_paswdaftar.getText().equals(jPasswordField_konfir.getText())){
            JOptionPane.showMessageDialog(null, "PASSWORD,KONFIRMASI BERBEDA !!!");
            jPasswordField_konfir.requestFocus();
        }
        else{            
            java.sql.Connection conn= new Koneksi.koneksi().connect();            
        try{
            java.sql.PreparedStatement stmt=conn.prepareStatement("insert into pengguna (nama,usia,username,password,konfirmasi,status ) values (?,?,?,?,?,?)");
            try{           
                stmt.setString(1,jTextField_nama.getText()); 
                stmt.setString(2,jTextField_usia.getText());
                stmt.setString(3,jTextField_usrdftr.getText());
                stmt.setString(4,jPasswordField_paswdaftar.getText());
                stmt.setString(5,jPasswordField_konfir.getText());
                stmt.setString(6,jLabel_status.getText());               
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"MENYIMPAN DATA","Pesan",JOptionPane.INFORMATION_MESSAGE);
                refresh2();
               
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"GAGAL MENYIMPAN DATA !!!","Pesan",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){

        }
        }
    }//GEN-LAST:event_jButton_buatActionPerformed

    private void jTextField_usrloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usrloginMouseClicked
        // TODO add your handling code here:
        jPasswordField_login.setText("");
        jPasswordField_login.requestFocus();
    }//GEN-LAST:event_jTextField_usrloginMouseClicked

    private void jTextField_usrloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usrloginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            jPasswordField_login.setText("");
            jPasswordField_login.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jPasswordField_login.setText("");
            jPasswordField_login.requestFocus();
        }
    }//GEN-LAST:event_jTextField_usrloginKeyPressed

    private void jTextField_usrloginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usrloginKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextField_usrlogin.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_usrloginKeyTyped

    private void jPasswordField_loginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_loginKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jPasswordField_login.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField_loginKeyTyped

    private void jTextField_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_namaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextField_nama.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
         if(!(karakter >= '0') && (karakter <= '9'))
        {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextField_namaKeyTyped

    private void jTextField_usiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usiaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextField_usia.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
         if(!(karakter >= '0') && (karakter <= '9'))
        {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextField_usiaKeyTyped

    private void jTextField_usrdftrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usrdftrKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextField_usrdftr.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_usrdftrKeyTyped

    private void jPasswordField_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_loginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_UP)
        {
            jTextField_usrlogin.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jButton_loginActionPerformed(null);
        }
    }//GEN-LAST:event_jPasswordField_loginKeyPressed

    private void jTextField_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_namaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            jTextField_usia.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jTextField_usia.requestFocus();
        }
    }//GEN-LAST:event_jTextField_namaKeyPressed

    private void jTextField_usiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usiaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_UP)
        {
            jTextField_nama.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            jTextField_usrdftr.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jTextField_usrdftr.requestFocus();
        }
    }//GEN-LAST:event_jTextField_usiaKeyPressed

    private void jTextField_usrdftrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usrdftrKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_UP)
        {
            jTextField_usia.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            jPasswordField_paswdaftar.setText("");
            jPasswordField_paswdaftar.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jPasswordField_paswdaftar.setText("");
            jPasswordField_paswdaftar.requestFocus();
        }
    }//GEN-LAST:event_jTextField_usrdftrKeyPressed

    private void jPasswordField_paswdaftarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_paswdaftarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_UP)
        {
            jTextField_usrdftr.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            jPasswordField_konfir.setText("");
            jPasswordField_konfir.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jPasswordField_konfir.setText("");
            jPasswordField_konfir.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField_paswdaftarKeyPressed

    private void jPasswordField_konfirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_konfirKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_UP)
        {
            jPasswordField_paswdaftar.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jButton_buatActionPerformed(null);
        }
    }//GEN-LAST:event_jPasswordField_konfirKeyPressed

    private void jPasswordField_paswdaftarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_paswdaftarKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jPasswordField_konfir.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField_paswdaftarKeyTyped

    private void jPasswordField_konfirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_konfirKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jPasswordField_konfir.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordField_konfirKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_batal;
    private javax.swing.JButton jButton_batalbuat;
    private javax.swing.JButton jButton_buat;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JLabel jLabel_status2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_konfir;
    private javax.swing.JPasswordField jPasswordField_login;
    private javax.swing.JPasswordField jPasswordField_paswdaftar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_nama;
    private javax.swing.JTextField jTextField_usia;
    private javax.swing.JTextField jTextField_usrdftr;
    private javax.swing.JTextField jTextField_usrlogin;
    private Kelas.tampilan tampilan1;
    private Kelas.tampilan tampilan2;
    private Kelas.tampilan tampilan3;
    private Kelas.tampilan tampilan4;
    private Kelas.tampilan tampilan5;
    private Kelas.tampilan tampilan6;
    private Kelas.tampilan tampilan7;
    private Kelas.tampilan tampilan8;
    // End of variables declaration//GEN-END:variables
}
