/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariboss
 */
public class pengetahuan extends javax.swing.JFrame {

    private DefaultTableModel DftTblModel;
    /**
     * Creates new form pengetahuan
     */
    public pengetahuan() {
        initComponents();
        setLocationRelativeTo(this);
        jTextField_idkerusakan.setEditable(false);
        jTextField_namakerusakan.setEditable(false);
        jTextField_kerusakan.setEditable(false);
        kerusakan();
        jTextArea_info.requestFocus();
        jTextField_gejala.requestFocus();
        jLabel_ID.setVisible(false);
        id();
        jButton_updategejala.setEnabled(false);
        jButton_simpan.setEnabled(true);
    }
   
    public void kerusakan(){
        java.sql.Connection conn = new Koneksi.koneksi().connect();
        try{
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet res = stmt.executeQuery("select *from kerusakan where Id ='"+jTextField_idkerusakan.getText()+"'");
            while(res.next()){
                jTextField_namakerusakan.setText(res.getString("nama"));
                jTextArea_info.setText(res.getString("info"));
                jTextArea_solusi.setText(res.getString("solusi"));
                
            }
        }catch(SQLException ex){
            
        }
    }
    
    public void refresh(){
        jTextField_kerusakan.setText("ENGINE MOUNTING");
        jComboBox_jenismobil.setSelectedItem("AUTOMATIC");
        jTextField_gejala.setText("");
        jTextField_nilai.setText("");
        jTextField_gejala.requestFocus();
        id();
        jButton_updategejala.setEnabled(false);
        jButton_simpan.setEnabled(true);
    }
      
    public void id(){        
        java.sql.Connection conn= new Koneksi.koneksi().connect();       
        try {            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select *from gejala ORDER BY Id DESC"); 
            if (rs.next()) {
                String nocust = rs.getString("Id").substring(4);
                String AN = "" + (Integer.parseInt(nocust) + 1);
                String Nol = "";
                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}               
                jLabel_ID.setText("GJL-" + Nol + AN);
            }else{
                jLabel_ID.setText("GJL-0001");
            }           
        }catch(Exception e){           
            JOptionPane.showMessageDialog(null, e);           
        }     
    }
    
    public void TampilData(){
        DftTblModel = new DefaultTableModel();
        DftTblModel.addColumn("ID");
        DftTblModel.addColumn("NAMA KERUSAKAN");
        DftTblModel.addColumn("JENIS MOBIL");
        DftTblModel.addColumn("GEJALA");
        DftTblModel.addColumn("NILAI GEJALA");
        jTable1.setModel(DftTblModel);
        java.sql.Connection conn = new Koneksi.koneksi().connect();
     try{
         java.sql.Statement stmt = conn.createStatement();
            String SQL = " select*from gejala";
         java.sql.ResultSet res=stmt.executeQuery(SQL);
         while(res.next()){
             DftTblModel.addRow(new Object[]{
                 res.getString("Id"),
                 res.getString("nama"),
                 res.getString("jenismobil"),
                 res.getString("gejala"),
                 res.getString("nilai")                 
             });
         }
     }catch(Exception e){
             }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_idkerusakan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_namakerusakan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_info = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_solusi = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton_updKerusakan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_kerusakan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton_updategejala = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField_gejala = new javax.swing.JTextField();
        jTextField_nilai = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_simpan = new javax.swing.JButton();
        jButton_new = new javax.swing.JButton();
        jComboBox_jenismobil = new javax.swing.JComboBox();
        jLabel_ID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        jTextField_idkerusakan.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_idkerusakan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_idkerusakan.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_idkerusakan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_idkerusakan.setText("KRSK-0001");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA KERUSAKAN");

        jTextField_namakerusakan.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_namakerusakan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_namakerusakan.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_namakerusakan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INFO");

        jTextArea_info.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea_info.setColumns(20);
        jTextArea_info.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_info.setRows(5);
        jTextArea_info.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea_infoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_infoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_info);

        jTextArea_solusi.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea_solusi.setColumns(20);
        jTextArea_solusi.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_solusi.setRows(5);
        jTextArea_solusi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_solusiKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea_solusi);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SOLUSI");

        jButton_updKerusakan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_updKerusakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        jButton_updKerusakan.setText("UPDATE");
        jButton_updKerusakan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_updKerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updKerusakanActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancel (2).png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(307, 307, 307)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton_updKerusakan, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jTextField_idkerusakan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_namakerusakan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idkerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_namakerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton_updKerusakan)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DATA KERUSAKAN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA KERUSAKAN");

        jTextField_kerusakan.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_kerusakan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_kerusakan.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_kerusakan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_kerusakan.setText("ENGINE MOUNTING");
        jTextField_kerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_kerusakanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JENIS MOBIL");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NAMA GEJALA");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NILAI KEYAKINAN");

        jButton_updategejala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_updategejala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        jButton_updategejala.setText("UPDATE");
        jButton_updategejala.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_updategejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updategejalaActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancel (2).png"))); // NOI18N
        jButton4.setText("EXIT");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField_gejala.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_gejala.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_gejala.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_gejala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_gejalaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_gejalaKeyTyped(evt);
            }
        });

        jTextField_nilai.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_nilai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nilai.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nilaiActionPerformed(evt);
            }
        });
        jTextField_nilai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nilaiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nilaiKeyTyped(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jTextField_search.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEARCH");

        jButton_simpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next.png"))); // NOI18N
        jButton_simpan.setText("SIMPAN");
        jButton_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_simpanActionPerformed(evt);
            }
        });

        jButton_new.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hand.png"))); // NOI18N
        jButton_new.setText("BARU");
        jButton_new.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_newActionPerformed(evt);
            }
        });

        jComboBox_jenismobil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox_jenismobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUTOMATIC", "MANUAL" }));

        jLabel_ID.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel_ID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_nilai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_kerusakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(jComboBox_jenismobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jTextField_gejala)))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton_new)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_updategejala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox_jenismobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_gejala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton_updategejala)
                    .addComponent(jButton_simpan)
                    .addComponent(jButton_new))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DATA GEJALA", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_kerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_kerusakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_kerusakanActionPerformed

    private void jButton_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_simpanActionPerformed
        // TODO add your handling code here:
        if(jTextField_gejala.getText().equals("")){
            JOptionPane.showMessageDialog(null, "GEJALA KOSONG !!!");
            jTextField_gejala.requestFocus();
        }
        else if(jTextField_nilai.getText().equals("")){
            JOptionPane.showMessageDialog(null, "NILAI KOSONG !!!");
            jTextField_nilai.requestFocus();
        }
        else{
            java.sql.Connection conn= new Koneksi.koneksi().connect();            
        try{
            java.sql.PreparedStatement stmt=conn.prepareStatement("insert into gejala (Id,nama,jenismobil,gejala,nilai) values (?,?,?,?,?)");
            try{           
                stmt.setString(1,jLabel_ID.getText()); 
                stmt.setString(2,jTextField_namakerusakan.getText());
                stmt.setString(3,jComboBox_jenismobil.getSelectedItem().toString());
                stmt.setString(4,jTextField_gejala.getText());
                stmt.setString(5,jTextField_nilai.getText());               
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"MENYIMPAN DATA","Pesan",JOptionPane.INFORMATION_MESSAGE);
                refresh();
               
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"GAGAL MENYIMPAN DATA !!!","Pesan",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){

        }
        }        
    }//GEN-LAST:event_jButton_simpanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_updKerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updKerusakanActionPerformed
        // TODO add your handling code here:
        java.sql.Connection conn = new Koneksi.koneksi().connect();
        try{
            java.sql.PreparedStatement stmt= conn.prepareStatement("update kerusakan set info=?,solusi=? where Id=? ");
            try{
                stmt.setString(1,jTextArea_info.getText());
                stmt.setString(2,jTextArea_solusi.getText());                
                stmt.setString(3,jTextField_idkerusakan.getText());                
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "DI UPDATE","Pesan",JOptionPane.INFORMATION_MESSAGE);
                kerusakan();
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "GAGAL DI UPDATE !!!","Pesan",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_jButton_updKerusakanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        TampilData();
    }//GEN-LAST:event_formWindowActivated

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        kerusakan();
        jTextArea_info.requestFocus();
        refresh();
        jTextField_gejala.requestFocus();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_newActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton_newActionPerformed

    private void jButton_updategejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updategejalaActionPerformed
        // TODO add your handling code here:
        java.sql.Connection conn = new Koneksi.koneksi().connect();
        try{
            java.sql.PreparedStatement stmt= conn.prepareStatement("update gejala set nama=?,jenismobil=?,gejala=?,nilai=? where Id=? ");
            try{
                stmt.setString(1,jTextField_kerusakan.getText());
                stmt.setString(2,jComboBox_jenismobil.getSelectedItem().toString());                
                stmt.setString(3,jTextField_gejala.getText());
                stmt.setString(4,jTextField_nilai.getText());
                stmt.setString(5,jLabel_ID.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "DI UPDATE","Pesan",JOptionPane.INFORMATION_MESSAGE);
                refresh();
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "GAGAL DI UPDATE !!!","Pesan",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_jButton_updategejalaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        jLabel_ID.setText(DftTblModel.getValueAt(baris,0).toString());
        jTextField_kerusakan.setText(DftTblModel.getValueAt(baris,1).toString());
        jComboBox_jenismobil.setSelectedItem(DftTblModel.getValueAt(baris,2).toString());
        jTextField_gejala.setText(DftTblModel.getValueAt(baris,3).toString());
        jTextField_nilai.setText(DftTblModel.getValueAt(baris,4).toString());
        jButton_updategejala.setEnabled(true);
        jButton_simpan.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_gejalaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_gejalaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
        {
            jTextField_nilai.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jTextField_nilai.requestFocus();
        }
    }//GEN-LAST:event_jTextField_gejalaKeyPressed

    private void jTextField_nilaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nilaiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_UP)
        {
            jTextField_gejala.requestFocus();
        }
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jButton_simpanActionPerformed(null);
        }
    }//GEN-LAST:event_jTextField_nilaiKeyPressed

    private void jTextArea_infoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_infoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea_infoKeyPressed

    private void jTextArea_infoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_infoKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextArea_info.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextArea_infoKeyTyped

    private void jTextArea_solusiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_solusiKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextArea_solusi.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextArea_solusiKeyTyped

    private void jTextField_gejalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_gejalaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextField_gejala.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_gejalaKeyTyped

    private void jTextField_nilaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nilaiKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextField_nilai.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
         if(!(karakter >= '0') && (karakter <= '9') && karakter ==',')
        {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextField_nilaiKeyTyped

    private void jTextField_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            DftTblModel = new DefaultTableModel();
            DftTblModel.addColumn("ID");
            DftTblModel.addColumn("NAMA KERUSAKAN");
            DftTblModel.addColumn("JENIS MOBIL");
            DftTblModel.addColumn("GEJALA");
            DftTblModel.addColumn("NILAI GEJALA");
            jTable1.setModel(DftTblModel);
            java.sql.Connection conn = new Koneksi.koneksi().connect();     
            try{         
                java.sql.Statement stmt = conn.createStatement();
                String SQL = " select*from gejala where gejala like '%"+jTextField_search.getText()+"%' or jenismobil like '%"+jTextField_search.getText()+"%'";
                java.sql.ResultSet res=stmt.executeQuery(SQL);
                while(res.next()){
                DftTblModel.addRow(new Object[]{
                res.getString("Id"),
                res.getString("nama"),
                res.getString("jenismobil"),
                res.getString("gejala"),
                res.getString("nilai")                              
                });         
                }         
                jButton_updategejala.setEnabled(true);                    
                jButton_simpan.setEnabled(false);
     
            }catch(Exception e){             
            }    
        }
        else{
            TampilData();
        }
    }//GEN-LAST:event_jTextField_searchKeyPressed

    private void jTextField_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        
         if(jTextField_search.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_searchKeyTyped

    private void jTextField_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengetahuan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_new;
    private javax.swing.JButton jButton_simpan;
    private javax.swing.JButton jButton_updKerusakan;
    private javax.swing.JButton jButton_updategejala;
    private javax.swing.JComboBox jComboBox_jenismobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_info;
    private javax.swing.JTextArea jTextArea_solusi;
    private javax.swing.JTextField jTextField_gejala;
    private javax.swing.JTextField jTextField_idkerusakan;
    private javax.swing.JTextField jTextField_kerusakan;
    private javax.swing.JTextField jTextField_namakerusakan;
    private javax.swing.JTextField jTextField_nilai;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
